---
- name: test bananas folder does not exist
  stat: path=/bananas
  register: banana_path
  failed_when: banana_path.stat.exists == true

- name: test that tcp 111 is not open
  command: nmap 10.0.0.11 -PN
  register: command_result
  failed_when: "'111/tcp' in command_result.stdout"

